---
title: "0427-resetmodel"
author: "yy"
date: "4/27/2022"
output: html_document
---

# 1. Introduction
In this project,I'd like to focus on Spatial problem of space & time taxi ride demand and time consumption for each taxi trip in New York.

## 1.1 Set up
```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
options(scipen = 999)
```

```{r setup_13, cache=TRUE, message=FALSE}
library(tidyverse)
library(sf)
library(stargazer)
library(lubridate)
library(tigris)
library(tidycensus)
library(viridis)
library(riem)
library(gridExtra)
library(knitr)
library(kableExtra)
library(caret)
library(RSocrata)
library(data.table)
library(pacman)
library(geosphere)
library(lubridate)
library(readr)
library(dplyr)
library(ggplot2)
library(gridExtra)
library(corrplot)
library(leaflet)
library(stringr)
library(rgdal)
library(mapview)
library(dplyr)
library(geodist)
library(lubridate)
library(tigris)
library(viridis)
library(riem)
library(gridExtra)
library(knitr)
library(mapview)
library(kableExtra)
library(RSocrata)
library(corrplot)
library(ggcorrplot)
library(gifski)
library(RSocrata)
library(spatstat)
library(raster)
library(spdep)
library(FNN)
library(gganimate)
library(corrplot)
library(RColorBrewer)
library(ggmap)
library(gmapsdistance)
library(datasets)
library(caret)
library(tree)
library(RSocrata)
library(tidyverse)
library(sf)
library(lubridate)
library(tigris)
library(tidycensus)
library(viridis)
library(riem)
library(gridExtra)
library(knitr)
library(kableExtra)
library(RSocrata)



plotTheme <- theme(
  plot.title =element_text(size=12),
  plot.subtitle = element_text(size=8),
  plot.caption = element_text(size = 6),
  axis.text.x = element_text(size = 10, angle = 45, hjust = 1),
  axis.text.y = element_text(size = 10),
  axis.title.y = element_text(size = 10),
  # Set the entire chart region to blank
  panel.background=element_blank(),
  plot.background=element_blank(),
  #panel.border=element_rect(colour="#F0F0F0"),
  # Format the grid
  panel.grid.major=element_line(colour="#D0D0D0",size=.2),
  axis.ticks=element_blank())

mapTheme <- theme(plot.title =element_text(size=12),
                  plot.subtitle = element_text(size=8),
                  plot.caption = element_text(size = 6),
                  axis.line=element_blank(),
                  axis.text.x=element_blank(),
                  axis.text.y=element_blank(),
                  axis.ticks=element_blank(),
                  axis.title.x=element_blank(),
                  axis.title.y=element_blank(),
                  panel.background=element_blank(),
                  panel.border=element_blank(),
                  panel.grid.major=element_line(colour = 'transparent'),
                  panel.grid.minor=element_blank(),
                  legend.direction = "vertical", 
                  legend.position = "right",
                  plot.margin = ggplot2::margin(1, 1, 1, 1, 'cm'),
                  legend.key.height = unit(1, "cm"), legend.key.width = unit(0.2, "cm"))


palette5 <- c("#eff3ff","#bdd7e7","#6baed6","#3182bd","#08519c")
palette4 <- c("#D2FBD4","#92BCAB","#527D82","#123F5A")
palette2 <- c("#6a51a3","#bcbddc")

options(tigris_class = "sf")
source("https://raw.githubusercontent.com/urbanSpatial/Public-Policy-Analytics-Landing/master/functions.r")


setwd("C:\\Users\\yaoye\\Desktop\\0506")

source("1_Package_Setup.R")
```


```{r get_census, message=FALSE, warning=FALSE, cache=TRUE, results = 'hide'}
# Install Census API Key
census_api_key("e79f3706b6d61249968c6ce88794f6f556e5bf3d", overwrite = TRUE)

# Import Census Info,especially commmuting data.
tracts16 <-  
  get_acs(geography = "tract", variables = c("B08301_001", #Means Of Transportation To Work,total
                                             "B08301_002", #Means Of Transportation To Work,Car, truck, or van,
                                             "B08301_010", #Means Of Transportation To Work, public transit
                                             "B08301_016", #Means Of Transportation To Work, taxicab
                                             
                #travel time to work ----public transit        
                                            
                                             "B08134_067",  #pub Travel time to work, 30-35 min
                                             "B08134_068",  #pub Travel time to work, 35-45 min
                                             "B08134_069",  #pub Travel time to work, 45-60 min
                                             "B08134_070",  #pub Travel time to work, >60 min
                
                 #travel time to work ----ride(car)        
                                            
                                             "B08134_017",  #car Travel time to work, 30-35 min
                                             "B08134_018",  #car Travel time to work, 35-45 min
                                             "B08134_019",  #car Travel time to work, 45-60 min
                                             "B08134_020",  #car Travel time to work, >60 min
                
                #travel time to work ----ride(taxi)        
                                            
                                             "B08134_117",  #taxi Travel time to work, 30-35 min
                                             "B08134_118",  #taxi Travel time to work, 35-45 min
                                             "B08134_119",  #taxi Travel time to work, 45-60 min
                                             "B08134_120",  #taxi Travel time to work, >60 min
                                             
                                            
                                             "B01003_001",   #Total Population
                                             "B19013_001",   #Median Household Income In The Past 12 Months
                                             "B01002_001",   #Median Age
                                             "C15010_001",   #Bachelor Degree or above
                                             
                #Race                        
                                             "B02001_002", #White people
                                             "B02001_003", #Black Or African American Alone
                                             "B02001_004", #American Indian And Alaska Native Alone
                                             "B02001_005", #Asian
                                             
                                             "B08111_017", #Num_Public Transportation_native
                                             "B08111_018",  #Num_Public Transportation_Foreign born
                
                #rent
                                              "B25059_001", #Upper Contract Rent
                                              "B25057_001", #Lower Contract Rent
                                              "B17005_002", #Income below poverty level
                                              "B16010_003", # less than high school, in labor force
                                              "B16010_016" ), # high school, in labor force
                year=2016, state=36, geometry=T,output = "wide")
                

tracts2016 <- tracts16%>%
  
   rename( Total_means_towork = B08301_001E,
           Car_towork = B08301_002E,
           Public_trans_towork = B08301_010E,
           Taxicab_towork = B08301_016E,
           
     
          pub_traveltime_30_35 = B08134_067E,
          pub_traveltime_35_45 = B08134_068E,
          pub_traveltime_45_60 = B08134_069E,
          pub_traveltime_60 = B08134_070E,
          
          car_traveltime_30_35 = B08134_017E,
          car_traveltime_35_45 = B08134_018E,
          car_traveltime_45_60 = B08134_019E,
          car_traveltime_60 = B08134_020E,
          
          taxi_traveltime_30_35 = B08134_117E,
          taxi_traveltime_35_45 = B08134_118E,
          taxi_traveltime_45_60 = B08134_119E,
          taxi_traveltime_60 = B08134_120E,
          
          
          Total_Pop =  B01003_001E,
          Median_income = B19013_001E,
          Median_age = B01002_001E,
          Bachelor_above = C15010_001E,
          
          White_American = B02001_002E,
          Black_American = B02001_003E,
          American_Indian = B02001_004E,
          Asian = B02001_005E,
          
          public_trans_native = B08111_017E,
          public_trans_foreign = B08111_018E,
          
          upper_rent = B25059_001E,
          lower_rent = B25057_001E,
          income_below_poverty = B17005_002E,
          belowhigh_onemploy = B16010_003E,
          abovehigh_onemploy = B16010_016E)%>%
  
  dplyr::select(Total_means_towork,Car_towork,Public_trans_towork,Taxicab_towork,
         
         pub_traveltime_30_35,pub_traveltime_35_45,pub_traveltime_45_60,pub_traveltime_60,
         car_traveltime_30_35,car_traveltime_35_45,car_traveltime_45_60,car_traveltime_60,
         taxi_traveltime_30_35,taxi_traveltime_35_45,taxi_traveltime_45_60,taxi_traveltime_60,
         
         Total_Pop,Median_income,Median_age,Bachelor_above,
         White_American,Black_American,American_Indian,Asian,
         public_trans_native,public_trans_foreign,
         upper_rent,lower_rent,income_below_poverty,belowhigh_onemploy,abovehigh_onemploy,
         GEOID,NAME,geometry)



clean_trancts_2016 <- tracts2016%>%
    st_transform('ESRI:102318')%>%
  mutate(Pct_publictrans_towork = Public_trans_towork / Total_means_towork,
         Pct_ride_towork = (Car_towork+Taxicab_towork) / Total_means_towork,
         pub_traveltime_30_60 = pub_traveltime_30_35 + pub_traveltime_35_45 + pub_traveltime_45_60,
         ride_traveltime_30_60 = car_traveltime_30_35 + car_traveltime_35_45 + car_traveltime_45_60 +
                                taxi_traveltime_30_35 + taxi_traveltime_35_45 + taxi_traveltime_45_60,
         ride_traveltime_60 = car_traveltime_60 + taxi_traveltime_60,
         pct_bachelor = Bachelor_above / Total_Pop,
         pct_white = White_American / Total_Pop,
         pct_black = Black_American / Total_Pop,
         pct_indian = American_Indian / Total_Pop,
         pct_asian = Asian / Total_Pop,
         pct_poverty = income_below_poverty / Total_Pop,
         pct_onemployment = (belowhigh_onemploy + abovehigh_onemploy) / Total_Pop,
         pct_pubtrans_native = public_trans_native / Public_trans_towork,
         pct_pubtrans_foreign = public_trans_foreign / Public_trans_towork
          )%>%
  dplyr::select (-Total_means_towork,-Car_towork,-Public_trans_towork,-Taxicab_towork,
                 -pub_traveltime_30_35,-pub_traveltime_35_45,-pub_traveltime_45_60,
                 -car_traveltime_30_35,-car_traveltime_35_45,-car_traveltime_45_60,-car_traveltime_60,
                 -taxi_traveltime_30_35,-taxi_traveltime_35_45,-taxi_traveltime_45_60,-taxi_traveltime_60,
                 -Bachelor_above,
                 -White_American,-Black_American,-American_Indian,-Asian,
                 -public_trans_native,-public_trans_foreign,
                 -income_below_poverty,-belowhigh_onemploy,-abovehigh_onemploy
                 )

```


```{r boundary,warning = FALSE, message = FALSE}

NYC_boundary <- st_read("Raw data/NYC Borough Boundaries.geojson")%>% st_transform('ESRI:102318')

clean_trancts_2016_only <- st_intersection(clean_trancts_2016,st_union(NYC_boundary))


NY_Tracts <- 
  clean_trancts_2016_only %>%
  as.data.frame() %>%
  distinct(GEOID, .keep_all = TRUE) %>%
  dplyr::select(GEOID, geometry) %>% 
  st_sf%>%
          st_transform(crs = 4326)

```




```{r ridership,warning = FALSE, message = FALSE}
taxitrip <- st_read("Raw data/NY-Ridership.csv")


taxitrip$passenger_count <-as.numeric(taxitrip$passenger_count)
taxitrip$trip_duration <-as.numeric(taxitrip$trip_duration)

  taxitrip$vendor_id <-as.numeric(taxitrip$vendor_id)
  taxitrip$dropoff_longitude <-as.numeric(taxitrip$dropoff_longitude)
  taxitrip$dropoff_latitude <-as.numeric(taxitrip$dropoff_latitude)
  taxitrip$pickup_longitude <-as.numeric(taxitrip$pickup_longitude)
  taxitrip$pickup_latitude <-as.numeric(taxitrip$pickup_latitude)
  


taxitrip <- taxitrip %>%
  mutate(pickup_datetime = ymd_hms(pickup_datetime),
         dropoff_datetime = ymd_hms(dropoff_datetime))

 taxitrip<- taxitrip %>% 
  mutate(interval60 = floor_date(ymd_hms(pickup_datetime), unit = "hour"),
         week = week(interval60),
         hour = hour(interval60),
         WeekDay = lubridate::wday(interval60, label=TRUE))

  taxitrip$weekend <- ifelse(taxitrip$WeekDay =="Sat" |taxitrip$WeekDay == "Sun","Weekend","not-Weekend")

```

```{r}
taxitrip_clean <- filter(taxitrip,passenger_count != 0)
taxitrip_clean <- filter(taxitrip_clean,passenger_count < 8)


#filter out outliers in trip duration.
mean(taxitrip_clean$trip_duration)
sd(taxitrip_clean$trip_duration)
taxitrip_clean <- filter(taxitrip_clean,trip_duration <= mean(trip_duration)+2*sd(trip_duration) & trip_duration >= mean(trip_duration)-2*sd(trip_duration))

#time of day
taxitrip_clean <- taxitrip_clean %>%
        mutate(time_of_day = case_when(hour(interval60) < 7 | hour(interval60) > 18 ~ "Overnight",
                                 hour(interval60) >= 7 & hour(interval60) < 10 ~ "Morning Rush Hour",
                                 hour(interval60) >= 10 & hour(interval60) < 15 ~ "Mid-Day",
                                 hour(interval60) >= 15 & hour(interval60) <= 18 ~ "Afternoon Rush Hour"))

```







```{r fig.height=6,fig.width=6}
weather.Data <- 
  riem_measures(station = "NYC", date_start = "2016-01-01", date_end = "2016-06-30")

weather.Data.clean <- weather.Data%>%
  dplyr::select(valid, tmpf, p01i, sknt)%>%
  replace(is.na(.), 0) %>%
    mutate(interval60 = ymd_h(substr(valid,1,13))) %>%
    mutate(week = week(interval60),
           dotw = lubridate::wday(interval60, label=TRUE)) %>%
    group_by(interval60) %>%
    summarize(Temperature = max(tmpf),
              Precipitation = sum(p01i),
              Wind_Speed = max(sknt)) %>%
    mutate(Temperature = ifelse(Temperature == 0, 42, Temperature))

grid.arrange(top = "Weather Data - NYC - Jan & June, 2016",
  ggplot(weather.Data.clean, aes(interval60,Precipitation)) + geom_line(colour = "#045a8d") + 
    labs(title="Percipitation", x="Hour", y="Percipitation") + plotTheme(),
  ggplot(weather.Data.clean, aes(interval60,Wind_Speed)) + geom_line(colour = "#045a8d") + 
    labs(title="Wind Speed", x="Hour", y="Wind Speed") + plotTheme(),
  ggplot(weather.Data.clean, aes(interval60,Temperature)) + geom_line(colour = "#045a8d") + 
    labs(title="Temperature", x="month", y="Temperature") + plotTheme()
  )

```



```{r}
#amenity
foodscrap <- st_read("https://data.cityofnewyork.us/resource/if26-z6xq.geojson")

foodscrap  <-
  foodscrap %>%
  dplyr::select(latitude, longitude) %>%
    na.omit() %>%
    st_as_sf(coords = c("longitude", "latitude"), crs = 4326, agr = "constant") %>%
    st_transform('ESRI:102318') %>%
    distinct()

foodscrap.sf <- foodscrap%>%
  dplyr::select(geometry) %>%
  na.omit() %>%
  distinct()

subwaystation <- st_read("Raw data/Subway Stations.geojson")%>%
  st_transform('ESRI:102318') %>%
    distinct()

subwaystation.sf <- subwaystation%>%
  dplyr::select(geometry)%>%
  na.omit()%>%
  distinct

wifi_hotspot <- st_read("https://data.cityofnewyork.us/resource/yjub-udmw.geojson")%>%
  st_transform('ESRI:102318') %>%
    distinct()

wifi_hotspot.sf <- wifi_hotspot%>%
  dplyr::select(geometry)%>%
  na.omit()%>%
  distinct

hotel <- st_read("https://data.cityofnewyork.us/resource/tjus-cn27.csv")%>%
   dplyr::select(latitude, longitude) %>%
  na.omit() 

hotel <- hotel[!apply(hotel == "", 1, all),]


hotel.sf <-hotel%>%
  st_as_sf(coords = c("longitude", "latitude"), crs = 4326, agr = "constant") %>%
    st_transform('ESRI:102318') %>%
  dplyr::select(geometry)%>%
  na.omit()%>%
    distinct()

healthystore <- st_read("https://data.cityofnewyork.us/resource/ud4g-9x9z.csv")


healthystore.sf <-healthystore%>%
  dplyr::select(longitude,latitude)%>%
  na.omit()

healthystore.sf <- healthystore.sf[!apply(healthystore.sf == "", 1, all),]

healthystore.sf <- healthystore.sf%>%
  st_as_sf(coords = c("longitude", "latitude"), crs = 4326, agr = "constant") %>%
    st_transform('ESRI:102318') %>%
  dplyr::select(geometry)%>%
    distinct()


#amenity data are: hotel.sf, wifi_hotspot.sf, subwaystation.sf ,foodscrap.sf
```



```{r}
sf::sf_use_s2(FALSE)
dat_census <- st_join(taxitrip_clean %>% 
          filter(is.na(pickup_latitude) == FALSE &
                   is.na(pickup_longitude) == FALSE &
                   is.na(dropoff_latitude) == FALSE &
                   is.na(dropoff_longitude) == FALSE) %>%
          st_as_sf(., coords = c("pickup_longitude","pickup_latitude"), crs = 4326),
        NY_Tracts %>%
          st_transform(crs=4326),
        join=st_intersects,
              left = TRUE) %>%
  rename(Origin.Tract = GEOID) %>%
  mutate(pickup_longitude = unlist(map(geometry, 1)),
         pickup_latitude = unlist(map(geometry, 2)))%>%
  as.data.frame() %>%
  dplyr::select(-geometry)%>%
  st_as_sf(., coords = c("dropoff_longitude", "dropoff_latitude"), crs = 4326) %>%
  st_join(., NY_Tracts %>%
            st_transform(crs=4326),
          join=st_intersects,
          left = TRUE) %>%
  rename(Destination.Tract = GEOID)  %>%
  mutate(dropoff_longitude = unlist(map(geometry, 1)),
         dropoff_latitude = unlist(map(geometry, 2)))%>%
  as.data.frame() %>%
  dplyr::select(-geometry)
```



```{r mean_trips_hist, warning = FALSE, message = FALSE }
dat_census %>%
        group_by(interval60, Origin.Tract, time_of_day) %>%
         tally()%>%
  group_by(Origin.Tract, time_of_day)%>%
  summarize(mean_trips = mean(n))%>%
  ggplot()+
  geom_histogram(aes(mean_trips), binwidth = 1)+
  labs(title="Mean Number Trips Per Tract in different time a day, NYC, 2016",
       x="Number of trips", 
       y="Frequency")+
  facet_wrap(~time_of_day)+
  plotTheme()
```


```{r}
#delete point outliers outside NYC boundary

taxi_clean_pickup <- dat_census%>%
          st_as_sf(., coords = c("pickup_longitude","pickup_latitude"), crs = 4326)


dat_census_cleanoutliers <- st_join(taxi_clean_pickup, NY_Tracts %>%
            st_transform(crs=4326),
          join=st_intersects,
          left = FALSE)%>%
   mutate(pickup_longitude = unlist(map(geometry, 1)),
         pickup_latitude = unlist(map(geometry, 2)))%>%
  as.data.frame()%>%
  dplyr::select(-GEOID,-geometry)


taxi_clean_dropoff <- dat_census_cleanoutliers%>%
          st_as_sf(., coords = c("dropoff_longitude","dropoff_latitude"), crs = 4326)

dat_census_cleanoutliers <- st_join(taxi_clean_dropoff, NY_Tracts %>%
            st_transform(crs=4326),
          join=st_intersects,
          left = FALSE)%>%
   mutate(dropoff_longitude = unlist(map(geometry, 1)),
         dropoff_latitude = unlist(map(geometry, 2)))%>%
  as.data.frame()%>%
  dplyr::select(-GEOID,-geometry)

dat_census_cleanoutliers_pickup <- dat_census_cleanoutliers%>%
   st_as_sf(., coords = c("pickup_longitude","pickup_latitude"), crs = 4326)


```


```{r}
st_c <- st_coordinates


#combine amenity features
dat_census_cleanoutliers_amenity <- dat_census_cleanoutliers%>%
  mutate(hotel_nn3 = nn_function(na.omit(st_c(dat_census_cleanoutliers_pickup)), na.omit(st_c(hotel.sf)), 3),
         wifi_nn3 = nn_function(na.omit(st_c(dat_census_cleanoutliers_pickup)), na.omit(st_c(wifi_hotspot.sf)), 3),
         subway_nn5 = nn_function(na.omit(st_c(dat_census_cleanoutliers_pickup)), na.omit(st_c(subwaystation.sf)), 5),
         store_nn4 = nn_function(na.omit(st_c(dat_census_cleanoutliers_pickup)), na.omit(st_c(healthystore.sf)), 4),
         fdscrap_nn3 = nn_function(na.omit(st_c(dat_census_cleanoutliers_pickup)), na.omit(st_c(foodscrap.sf)), 3))
 
```


```{r fig.height=10, fig.width=10}
ggplot()+
  geom_sf(data = NY_Tracts %>%
          st_transform(crs=4326))+
  geom_point(data = dat_census_cleanoutliers_amenity %>%
              group_by(Origin.Tract, pickup_latitude, pickup_longitude, weekend, time_of_day) %>%
              tally(),
            aes(x=pickup_longitude, y = pickup_latitude, color = n), 
            fill = "transparent", alpha = 0.4, size = 0.3)+
  scale_colour_viridis(direction = -1,
  discrete = FALSE, option = "D")+
  ylim(min(dat_census_cleanoutliers_amenity$pickup_latitude), max(dat_census_cleanoutliers_amenity $pickup_latitude))+
  xlim(min(dat_census_cleanoutliers_amenity $pickup_longitude), max(dat_census_cleanoutliers_amenity $pickup_longitude))+
  facet_grid(weekend ~ time_of_day)+
  labs(title="Taxi trips per hr by tracts. NYC, 2016")+
  mapTheme()
```


panel

```{r}
length(unique(dat_census_cleanoutliers_amenity$interval60)) * length(unique(dat_census_cleanoutliers_amenity$Origin.Tract))



set.seed(123)
dat_census_sample <- sample_n(dat_census_cleanoutliers_amenity, 100000)




study.panel <- 
  expand.grid(interval60=unique(dat_census_sample$interval60), 
              Origin.Tract = unique(dat_census_sample$Origin.Tract)) %>%
  left_join(., dat_census_sample %>%
              dplyr::select(Origin.Tract, pickup_longitude, pickup_latitude )%>%
              distinct() %>%
              group_by(Origin.Tract) %>%
              dplyr::slice(1))
nrow(study.panel)  
```

```{r}
#join weather and trip count
ride.panel_0506 <- 
  dat_census_cleanoutliers_amenity %>%
  mutate(Trip_Counter = 1) %>%
  right_join(study.panel) %>% 
  group_by(interval60, Origin.Tract) %>%
  summarize(Trip_Count = sum(Trip_Counter, na.rm=T)) %>%
  left_join(weather.Data.clean, by = "interval60") %>%
  ungroup() %>%
  filter(is.na(Origin.Tract) == FALSE)%>%
  left_join(clean_trancts_2016_only, by = c("Origin.Tract" = "GEOID"))%>% 
          st_sf()




#creat time lag
ride.panel_lag_0506 <- 
  ride.panel_0506 %>% 
  arrange(Origin.Tract, interval60) %>% 
  mutate(lagHour = dplyr::lag(Trip_Count,1),
         lag2Hours = dplyr::lag(Trip_Count,2),
         lag3Hours = dplyr::lag(Trip_Count,3),
         lag4Hours = dplyr::lag(Trip_Count,4),
         lag12Hours = dplyr::lag(Trip_Count,12),
         lag1day = dplyr::lag(Trip_Count,24))%>% 
   ungroup()


as.data.frame(ride.panel_lag_0506) %>%
    group_by(interval60) %>% 
    summarise_at(vars(starts_with("lag"), "Trip_Count"), mean, na.rm = TRUE) %>%
    gather(Variable, Value, -interval60, -Trip_Count) %>%
    mutate(Variable = factor(Variable, levels=c("lagHour","lag2Hours","lag3Hours","lag4Hours",                                           "lag12Hours","lag1day")))%>%
    group_by(Variable) %>%  
    summarize(correlation = round(cor(Value, Trip_Count),2))%>%
   kable(caption = "Time Lag Correlation") %>%
    kable_styling("striped", full_width = F)


```



```{r}
panel0506 <- 
  dat_census_cleanoutliers_amenity %>%
  left_join(ride.panel_lag_0506) %>%
  filter(is.na(Origin.Tract) == FALSE) %>%
  filter(is.na(Destination.Tract) == FALSE)

panel0506_clean <- 
  na.omit(panel0506)
```



```{r}
panel0506%>%
  dplyr::select(-id,-pickup_latitude,-pickup_longitude,-pickup_datetime,-dropoff_latitude,-dropoff_longitude,-dropoff_datetime,-vendor_id)%>%
  gather(Variable, Value, -trip_duration) %>% 
   ggplot(aes(Value, trip_duration)) +
     geom_point(size = .5) + geom_smooth(method = "lm", se=F, colour = "#FA7800") +
     facet_wrap(~Variable, ncol = 3, scales = "free") +
     labs(title = "trip duration as a function of continuous variables") +
     plotTheme()


numericVars <- 
  select_if(panel2222, is.numeric) %>% na.omit()%>%
  dplyr::select(-pickup_latitude,-pickup_longitude,-dropoff_latitude,-dropoff_longitude)


#update.packages()
ggcorrplot(
  cor(numericVars), 
  p.mat = cor_pmat(numericVars),
  colors = c("#88419d", "#fff7ec", "#08519c"),
  type="lower",
  insig = "blank") +  
    labs(title = "Correlation across numeric variables") 

```


 
# Model building

## for trip duration
```{r}
source("1_Package_Setup.R")

panel.sample <- sample_n(panel0506_clean, 20000)

data_split <- initial_split(panel.sample, strata = "trip_duration", prop = 0.75)
trip_train <- training(data_split)
trip_test  <- testing(data_split)
```

###OLS Regression
```{r}
#trip feature+ weather+ demographic
reg1 <-
  lm(trip_duration ~ store_and_fwd_flag + hour + WeekDay + week + passenger_count+ weekend+ time_of_day+Temperature + Precipitation + Wind_Speed+pub_traveltime_60 + Total_Pop + Median_income +Median_age + upper_rent + Pct_publictrans_towork + pct_bachelor + pct_white +pct_onemployment ,  data=trip_train)


#trip feature+ weather+ amenity+timelag
reg2 <- 
  lm(trip_duration ~ store_and_fwd_flag + hour + WeekDay + week + passenger_count+ weekend+ time_of_day+Temperature + Precipitation + Wind_Speed + hotel_nn3 + wifi_nn3 + subway_nn5 + fdscrap_nn3 + store_nn4+lagHour	+ lag2Hours +	lag3Hours +	lag4Hours	+ lag12Hours,  data=trip_train)

#trip feature+ weather+ amenity+timelag +ACS
reg3 <- 
  lm(trip_duration ~ store_and_fwd_flag +vendor_id + passenger_count + hour + WeekDay + weekend+ time_of_day +  hotel_nn3 + wifi_nn3 + subway_nn5 + fdscrap_nn3 + pub_traveltime_60 + Total_Pop + Median_income +Median_age + upper_rent + Pct_publictrans_towork + pct_bachelor + pct_white +pct_onemployment + lag2Hours +	lag3Hours +	lag4Hours +	Temperature + Precipitation + Wind_Speed,  data=trip_train)

```


```{r}
summary(reg1)
summary(reg2)
summary(reg3)
```

```{r}
stargazer(reg1, type = "text",title = "OLS Regression Results First Model", align=TRUE, no.space=TRUE)
summary(reg1)
```
```{r}
stargazer(reg2, type = "text",title = "OLS Regression Results Second Model", align=TRUE, no.space=TRUE)
summary(reg2)
```

```{r}
stargazer(reg3, type = "text",title = "OLS Regression Results Third Model", align=TRUE, no.space=TRUE)
summary(reg3)
```

```{r}
Performance_OLS_reg1 <-
  trip_test%>%
  mutate(Predict_duration_reg1 = predict(reg1, trip_test),
         Error_duration_reg1 = Predict_duration_reg1 - trip_duration,
         AbsError_reg1 = abs(Predict_duration_reg1 - trip_duration),
         APE_reg1 = (abs(Predict_duration_reg1 - trip_duration)) / trip_duration) 

MAE_OLSreg1 <- mean(Performance_OLS_reg1$AbsError_reg1, na.rm = T)

MAPE_OLSreg1  <- mean(Performance_OLS_reg1$APE_reg1, na.rm = T)

acc1 <- data.frame(MAE_OLSreg1, MAPE_OLSreg1)
ols_acc_table1 <- kable(acc1, caption = "OLS Error Metrics") %>% 
  kable_styling(full_width = F)
ols_acc_table1

```



```{r}
Performance_OLS_reg2 <-
  trip_test%>%
  mutate(Predict_duration_reg2 = predict(reg2, trip_test),
         Error_duration_reg2 = Predict_duration_reg2 - trip_duration,
         AbsError_reg2 = abs(Predict_duration_reg2 - trip_duration),
         APE_reg2 = (abs(Predict_duration_reg2 - trip_duration)) / trip_duration) 

MAE_OLSreg2 <- mean(Performance_OLS_reg2$AbsError_reg2, na.rm = T)

MAPE_OLSreg2 <- mean(Performance_OLS_reg2$APE_reg2, na.rm = T)

acc2 <- data.frame(MAE_OLSreg2, MAPE_OLSreg2)
ols_acc_table2 <- kable(acc2, caption = "OLS Error Metrics") %>% 
  kable_styling(full_width = F)

ols_acc_table2
```

```{r}
Performance_OLS_reg3 <-
  trip_test%>%
  mutate(Predict_duration_reg3 = predict(reg3, trip_test),
         Error_duration_reg3 = Predict_duration_reg3 - trip_duration,
         AbsError_reg3 = abs(Predict_duration_reg3 - trip_duration),
         APE_reg3 = (abs(Predict_duration_reg3 - trip_duration)) / trip_duration) 

MAE_OLSreg3 <- mean(Performance_OLS_reg3$AbsError_reg3, na.rm = T)

MAPE_OLSreg3  <- mean(Performance_OLS_reg3$APE_reg3, na.rm = T)

acc <- data.frame(MAE_OLSreg3, MAPE_OLSreg3)
ols_acc_table3 <- kable(acc, caption = "OLS Error Metrics") %>% 
  kable_styling(full_width = F)
ols_acc_table3

```



```{r}
fitControl <- trainControl(method = "cv", number = 10)
set.seed(825)
OLS_reg1.cv <- 
  train(trip_duration ~ store_and_fwd_flag + hour + WeekDay + week + passenger_count+ weekend+ time_of_day+Temperature + Precipitation + Wind_Speed+pub_traveltime_60 + Total_Pop + Median_income +Median_age + upper_rent + Pct_publictrans_towork + pct_bachelor + pct_white +pct_onemployment ,  data=trip_train,
        method = "lm", trControl = fitControl, na.action = na.pass)


OLS_reg1.cv
OLS_reg1.cv$resample[1:10,]

MAE_reg <- OLS_reg1.cv$resample
ggplot(MAE_reg, aes(MAE)) + 
  geom_histogram(color="black", binwidth = 0.2, fill="#5192B0") +
  labs(title = "Histogram of MAEs of Cross Validation", subtitle = "OLS regression reg1",  x = "Mean Absolute Error (MAE)", y= "Count") +
  plotTheme()
```





```{r}


#panel.sample <- sample_n(panel0506_clean, 100000)

#data_split <- initial_split(panel.sample, strata = "trip_duration", prop = 0.75)
#trip_train.sample <- training(data_split)
#trip_test.sample  <- testing(data_split)
```





```{r}
rf_model1 <- randomForest(trip_duration ~ store_and_fwd_flag + hour + WeekDay + week + passenger_count+ weekend+ time_of_day+Temperature + Precipitation + Wind_Speed+pub_traveltime_60 + Total_Pop + Median_income +Median_age + upper_rent + Pct_publictrans_towork + pct_bachelor + pct_white +pct_onemployment ,  data=trip_train, 
                         ntree=50,
                         mtry=20,
                         na.action=na.exclude,
                         bootstrap=T)
rf_model1
library(randomForest)
library(caret)
library(readr)
library(car)
saveRDS(rf_model1,'model.rds')
rf_model1$importance


RF_model_rf1 <- 
  trip_test %>%
  mutate(rf_predict_md1 = predict(rf_model1,trip_test),
         rf_error_md1 = rf_predict_md1 - trip_duration,
         rf_absError_md1 = abs(rf_predict_md1 - trip_duration),
         rf_APE_md1 = (abs(rf_predict_md1 - trip_duration)) / trip_duration) 

rf1_MAE <- mean(RF_model_rf1$rf_absError_md1, na.rm = T)
rf1_MAPE <- mean(RF_model_rf1$rf_APE_md1 , na.rm = T)
rf1_acc <- data.frame(rf1_MAE, rf1_MAPE)
rf1_acc_table <- kable(rf1_acc, caption="Random Forest Error Metrics - first model") %>% 
  kable_styling(full_width = F)
rf1_acc_table
```




```{r}
rf_model2 <- randomForest(trip_duration ~ store_and_fwd_flag + hour + WeekDay + week + passenger_count+ weekend+ time_of_day+Temperature + Precipitation + Wind_Speed + hotel_nn3 + wifi_nn3 + subway_nn5 + fdscrap_nn3 + store_nn4+lagHour	+ lag2Hours +	lag3Hours +	lag4Hours	+ lag12Hours,  data=trip_train, 
                         ntree=50,
                         mtry=20,
                         na.action=na.exclude,
                         bootstrap=T)
rf_model2


rf_model2$importance


RF_model_rf2 <- 
  trip_test %>%
  mutate(rf_predict_md2 = predict(rf_model2,trip_test),
         rf_error_md2 = rf_predict_md2 - trip_duration,
         rf_absError_md2 = abs(rf_predict_md2 - trip_duration),
         rf_APE_md2 = (abs(rf_predict_md2 - trip_duration)) / trip_duration) 

rf2_MAE <- mean(RF_model_rf2$rf_absError_md2, na.rm = T)
rf2_MAPE <- mean(RF_model_rf2$rf_APE_md2 , na.rm = T)
rf2_acc <- data.frame(rf2_MAE, rf2_MAPE)
rf2_acc_table <- kable(rf2_acc, caption="Random Forest Error Metrics - second model") %>% 
  kable_styling(full_width = F)
rf2_acc_table

```


```{r}
rf_model3 <- randomForest(trip_duration ~ store_and_fwd_flag +vendor_id + passenger_count + hour + WeekDay + weekend+ time_of_day +  hotel_nn3 + wifi_nn3 + subway_nn5 + fdscrap_nn3 + pub_traveltime_60 + Total_Pop + Median_income +Median_age + upper_rent + Pct_publictrans_towork + pct_bachelor + pct_white +pct_onemployment + lag2Hours +	lag3Hours +	lag4Hours +	Temperature + Precipitation + Wind_Speed,  data=trip_train, 
                         ntree=50,
                         mtry=20,
                         na.action=na.exclude,
                         bootstrap=T)
rf_model3


rf_model3$importance


RF_model_rf3 <- 
  trip_test %>%
  mutate(rf_predict_md3 = predict(rf_model3,trip_test),
         rf_error_md3 = rf_predict_md3 - trip_duration,
         rf_absError_md3 = abs(rf_predict_md3 - trip_duration),
         rf_APE_md3 = (abs(rf_predict_md3 - trip_duration)) / trip_duration) 

rf3_MAE <- mean(RF_model_rf3$rf_absError_md3, na.rm = T)
rf3_MAPE <- mean(RF_model_rf3$rf_APE_md3 , na.rm = T)
rf3_acc <- data.frame(rf3_MAE, rf3_MAPE)
rf3_acc_table <- kable(rf3_acc, caption="Random Forest Error Metrics - third model") %>% 
  kable_styling(full_width = F)
rf3_acc_table

```


```{r}
poisson_reg1 <- glm(formula = 
                      trip_duration ~ store_and_fwd_flag + hour + WeekDay + week + passenger_count+ weekend+ time_of_day+Temperature + Precipitation + Wind_Speed+pub_traveltime_60 + Total_Pop + Median_income +Median_age + upper_rent + Pct_publictrans_towork + pct_bachelor + pct_white +pct_onemployment ,  data=trip_train, 
                    family = poisson)

stargazer(poisson_reg1, type = "text",title = "Poisson Regression Results", align=TRUE, no.space=TRUE)

EP_model_poisson <-
  trip_test%>%
  mutate(PS.Predict_md1 = predict(poisson_reg1, trip_test),
         PS.Error_md1 = PS.Predict_md1 - trip_duration,
         PS.AbsError_md1 = abs(PS.Predict_md1 - trip_duration),
         PS.APE_md1 = (abs(PS.Predict_md1- trip_duration)) / trip_duration) 

poisson_MAE <- mean(EP_model_poisson$PS.AbsError_md1, na.rm = T)
poisson_MAPE <- mean(EP_model_poisson$PS.APE_md1, na.rm = T)
poisson_acc <- data.frame(poisson_MAE, poisson_MAPE)
poisson_acc_table <- kable(poisson_acc, caption="Poisson Error Metrics - first model") %>% 
  kable_styling(full_width = F)
poisson_acc_table
```

```{r}
poisson_reg2 <- glm(formula = 
                      trip_duration ~ store_and_fwd_flag + hour + WeekDay + week + passenger_count+ weekend+ time_of_day+Temperature + Precipitation + Wind_Speed + hotel_nn3 + wifi_nn3 + subway_nn5 + fdscrap_nn3 + store_nn4+lagHour	+ lag2Hours +	lag3Hours +	lag4Hours	+ lag12Hours,  data=trip_train, 
                    family = poisson)

stargazer(poisson_reg2, type = "text",title = "Poisson Regression Results - second model", align=TRUE, no.space=TRUE)

EP_model_poisson2 <-
  trip_test%>%
  mutate(PS.Predict_md2 = predict(poisson_reg2, trip_test),
         PS.Error_md2 = PS.Predict_md2 - trip_duration,
         PS.AbsError_md2 = abs(PS.Predict_md2 - trip_duration),
         PS.APE_md2 = (abs(PS.Predict_md2- trip_duration)) / trip_duration) 

poisson_MAE2 <- mean(EP_model_poisson2$PS.AbsError_md2, na.rm = T)
poisson_MAPE2 <- mean(EP_model_poisson2$PS.APE_md2, na.rm = T)
poisson_acc2 <- data.frame(poisson_MAE2, poisson_MAPE2)
poisson_acc_table2 <- kable(poisson_acc2, caption="Poisson Error Metrics - second model") %>% 
  kable_styling(full_width = F)
poisson_acc_table2
```

```{r}
poisson_reg3 <- glm(formula = 
                      trip_duration ~ store_and_fwd_flag +vendor_id + passenger_count + hour + WeekDay + weekend+ time_of_day +  hotel_nn3 + wifi_nn3 + subway_nn5 + fdscrap_nn3 + pub_traveltime_60 + Total_Pop + Median_income +Median_age + upper_rent + Pct_publictrans_towork + pct_bachelor + pct_white +pct_onemployment + lag2Hours +	lag3Hours +	lag4Hours +	Temperature + Precipitation + Wind_Speed,  data=trip_train, 
                    family = poisson)

stargazer(poisson_reg3, type = "text",title = "Poisson Regression Results - third model", align=TRUE, no.space=TRUE)

EP_model_poisson3 <-
  trip_test%>%
  mutate(PS.Predict_md3 = predict(poisson_reg3, trip_test),
         PS.Error_md3 = PS.Predict_md3 - trip_duration,
         PS.AbsError_md3 = abs(PS.Predict_md3 - trip_duration),
         PS.APE_md3 = (abs(PS.Predict_md3- trip_duration)) / trip_duration) 

poisson_MAE3 <- mean(EP_model_poisson3$PS.AbsError_md3, na.rm = T)
poisson_MAPE3 <- mean(EP_model_poisson3$PS.APE_md3, na.rm = T)
poisson_acc3 <- data.frame(poisson_MAE3, poisson_MAPE3)
poisson_acc_table3 <- kable(poisson_acc3, caption="Poisson Error Metrics - third model") %>% 
  kable_styling(full_width = F)
poisson_acc_table3
```



#model performance/ cross validation

##OLS regression
 k-fold cross validation for OLS model
```{r}
fitControl <- trainControl(method = "cv", number = 100)
set.seed(825)
OLS_reg1.cv_1 <- 
  train(trip_duration ~ store_and_fwd_flag + hour + WeekDay + week + passenger_count+ weekend+ time_of_day+Temperature + Precipitation + Wind_Speed+pub_traveltime_60 + Total_Pop + Median_income +Median_age + upper_rent + Pct_publictrans_towork + pct_bachelor + pct_white +pct_onemployment ,  data=trip_train,
        method = "lm", trControl = fitControl, na.action = na.pass)

OLS_reg1.cv
OLS_reg1.cv$resample[1:10,] 

MAE_reg1 <- OLS_reg1.cv$resample
ggplot(MAE_reg1, aes(MAE)) + 
  geom_histogram(color="black", binwidth = 0.5, fill="#5192B0") +
  labs(title = "Histogram of MAEs of Cross Validation", subtitle = "OLS regression model 1",  x = "Mean Absolute Error (MAE)", y= "Count") +
  plotTheme()


#regression 2
OLS_reg2.cv <- 
  train(trip_duration ~ store_and_fwd_flag + hour + WeekDay + week + passenger_count+ weekend+ time_of_day+Temperature + Precipitation + Wind_Speed + hotel_nn3 + wifi_nn3 + subway_nn5 + fdscrap_nn3 + store_nn4+lagHour	+ lag2Hours +	lag3Hours +	lag4Hours	+ lag12Hours,  data=trip_train,
        method = "lm", trControl = fitControl, na.action = na.pass)

OLS_reg2.cv
OLS_reg2.cv$resample[1:10,] 

MAE_reg2 <- OLS_reg2.cv$resample
ggplot(MAE_reg2, aes(MAE)) + 
  geom_histogram(color="black", binwidth = 0.5, fill="#5192B0") +
  labs(title = "Histogram of MAEs of Cross Validation", subtitle = "OLS regression model 2",  x = "Mean Absolute Error (MAE)", y= "Count") +
  plotTheme()


#regression 3
OLS_reg3.cv <- 
  train(trip_duration ~ store_and_fwd_flag +vendor_id + passenger_count + hour + WeekDay + weekend+ time_of_day +  hotel_nn3 + wifi_nn3 + subway_nn5 + fdscrap_nn3 + pub_traveltime_60 + Total_Pop + Median_income +Median_age + upper_rent + Pct_publictrans_towork + pct_bachelor + pct_white +pct_onemployment + lag2Hours +	lag3Hours +	lag4Hours +	Temperature + Precipitation + Wind_Speed,  data=trip_train,
        method = "lm", trControl = fitControl, na.action = na.pass)

OLS_reg3.cv
OLS_reg3.cv$resample[1:10,] 

MAE_reg3 <- OLS_reg3.cv$resample
ggplot(MAE_reg3, aes(MAE)) + 
  geom_histogram(color="black", binwidth = 0.5, fill="#5192B0") +
  labs(title = "Histogram of MAEs of Cross Validation", subtitle = "OLS regression model 3",  x = "Mean Absolute Error (MAE)", y= "Count") +
  plotTheme()
```
#random forest
```{r}
ggplot(RF_model_rf1, aes(x=trip_duration, y=rf_predict_md1)) + 
  geom_point()+
  geom_smooth(method=lm) +
  labs(title = "Predicted trip duration vs. Real trip duration",
         y="Predicted trip duration",
         x="real trip duration",
       subtitle = "Random Forest model 1")  + 
  plotTheme()
```

```{r}
ggplot(RF_model_rf2, aes(x=trip_duration, y=rf_predict_md2)) + 
  geom_point()+
  geom_smooth(method=lm) +
  labs(title = "Predicted trip duration vs. Real trip duration",
         y="Predicted trip duration",
         x="real trip duration",
       subtitle = "Random Forest model 2")  + 
  plotTheme()
```
```{r}
ggplot(RF_model_rf3, aes(x=trip_duration, y=rf_predict_md3)) + 
  geom_point()+
  geom_smooth(method=lm) +
  labs(title = "Predicted trip duration vs. Real trip duration",
         y="Predicted trip duration",
         x="real trip duration",
       subtitle = "Random Forest model 3")  + 
  plotTheme()
```

```{r}
rf1.cv <- 
  train(trip_duration ~ store_and_fwd_flag + hour + WeekDay + week + passenger_count+ weekend+ time_of_day+Temperature + Precipitation + Wind_Speed + hotel_nn3 + wifi_nn3 + subway_nn5 + fdscrap_nn3 + store_nn4+lagHour	+ lag2Hours +	lag3Hours +	lag4Hours	+ lag12Hours,  data=trip_train,
         method = "rpart", trControl = fitControl, na.action = na.pass)


MAE_rf1 <- rf1.cv $resample
ggplot(MAE_rf1, aes(MAE)) + 
  geom_histogram(color="black", binwidth = 0.5, fill="#5192B0") +
  labs(title = "Histogram of MAEs of Cross Validation", subtitle = "Random forest model 1",  x = "Mean Absolute Error (MAE)", y= "Count") +
  plotTheme()
```


```{r}
rf2.cv <- 
  train(trip_duration ~ store_and_fwd_flag + hour + WeekDay + week + passenger_count+ weekend+ time_of_day+Temperature + Precipitation + Wind_Speed + hotel_nn3 + wifi_nn3 + subway_nn5 + fdscrap_nn3 + store_nn4+lagHour	+ lag2Hours +	lag3Hours +	lag4Hours	+ lag12Hours,  data=trip_train,
         method = "rpart", trControl = fitControl, na.action = na.pass)


MAE_rf2 <- rf2.cv $resample
ggplot(MAE_rf2, aes(MAE)) + 
  geom_histogram(color="black", binwidth = 0.5, fill="#5192B0") +
  labs(title = "Histogram of MAEs of Cross Validation", subtitle = "Random forest model 2",  x = "Mean Absolute Error (MAE)", y= "Count") +
  plotTheme()
```
```{r}
rf3.cv <- 
  train(trip_duration ~ store_and_fwd_flag +vendor_id + passenger_count + hour + WeekDay + weekend+ time_of_day +  hotel_nn3 + wifi_nn3 + subway_nn5 + fdscrap_nn3 + pub_traveltime_60 + Total_Pop + Median_income +Median_age + upper_rent + Pct_publictrans_towork + pct_bachelor + pct_white +pct_onemployment + lag2Hours +	lag3Hours +	lag4Hours +	Temperature + Precipitation + Wind_Speed,  data=trip_train,
         method = "rpart", trControl = fitControl, na.action = na.pass)


MAE_rf3 <- rf3.cv $resample
ggplot(MAE_rf3, aes(MAE)) + 
  geom_histogram(color="black", binwidth = 0.5, fill="#5192B0") +
  labs(title = "Histogram of MAEs of Cross Validation", subtitle = "Random forest model 3",  x = "Mean Absolute Error (MAE)", y= "Count") +
  plotTheme()
```
